import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Echo",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed flex flex-col gap-2">
        {children}
      </div>
    </section>
  );
}

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-12 flex flex-col gap-8">
        <div>
          <Link href="/login" className="text-sm text-primary hover:underline">&larr; Back</Link>
          <h1 className="text-3xl font-bold tracking-tight mt-4">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mt-1">Last updated: October 3, 2026</p>
        </div>

        <Section title="Acceptance of Terms">
          <p>By signing in to Echo (&ldquo;the app&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) with your Google account, you agree to these Terms of Service and the accompanying <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.</p>
        </Section>

        <Section title="Description of Service">
          <p>
            Echo reads your primary Gmail inbox and drafts reply suggestions using an AI model,
            grounded in documents you choose to upload as a knowledge base. Echo never sends an
            email on your behalf automatically — every reply is sent only after you review, edit
            if needed, and explicitly click Send.
          </p>
        </Section>

        <Section title="Your Responsibilities">
          <ul className="list-disc list-inside flex flex-col gap-1">
            <li>You must supply your own API key(s) for the AI provider(s) you choose to use (Groq, OpenAI, and/or Gemini). Any usage costs charged by that provider are your responsibility, not ours.</li>
            <li>You are solely responsible for reviewing every AI-drafted reply before sending it. Echo does not verify the factual accuracy of generated content.</li>
            <li>Don&apos;t upload documents you don&apos;t have the right to use, and don&apos;t use Echo for any unlawful purpose.</li>
          </ul>
        </Section>

        <Section title="AI-Generated Content Disclaimer">
          <p>
            Replies are generated by third-party AI models and may be inaccurate, outdated, or
            inappropriate for your intended recipient. Always review a draft in full before
            sending it.
          </p>
        </Section>

        <Section title="No Warranty">
          <p>Echo is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any kind, express or implied, including fitness for a particular purpose or uninterrupted availability.</p>
        </Section>

        <Section title="Limitation of Liability">
          <p>To the maximum extent permitted by law, we are not liable for any damages arising from your use of Echo, including but not limited to the content of any email sent through it.</p>
        </Section>

        <Section title="Account Termination">
          <p>You may stop using Echo at any time by revoking its access from your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google Account&apos;s security settings</a>. We may suspend or terminate access for accounts that abuse the service.</p>
        </Section>

        <Section title="Changes to These Terms">
          <p>We may update these terms as Echo evolves. Continuing to use Echo after a change constitutes acceptance of the updated terms.</p>
        </Section>

        <Section title="Contact Us">
          <p>Questions about these terms can be sent to <a href="mailto:romancobblepot@gmail.com" className="text-primary hover:underline">romancobblepot@gmail.com</a>.</p>
        </Section>
      </div>
    </main>
  );
}
